name: Flutter Build APK

on:
  push:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # 1. Копирование кода (Обновлено до v4)
    - uses: actions/checkout@v4

    # 2. Установка Java 17 (Обновлено до v4)
    - name: Set up JDK
      uses: actions/setup-java@v4
      with:
        distribution: 'zulu'
        java-version: '17'

    # 3. Установка Flutter
    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        channel: 'stable'

    # 4. Скачивание библиотек
    - name: Install dependencies
      run: flutter pub get

    # 5. Сборка APK
    - name: Build APK
      run: flutter build apk --split-per-abi

    # 6. Загрузка готовых файлов в артефакты (Обновлено до v4)
    - name: Upload APK Artifact
      uses: actions/upload-artifact@v4
      with:
        name: release-apk
        path: build/app/outputs/flutter-apk/*-release.apk
